/** Les 99 noms d'Allah (Asma ul-Husna). Liste canonique complète (99 entrées). */

export interface Name99 {
  transliteration: string;
  arabic: string;
  translation: string;
  description: string;
  /** URL du fichier audio (récitation) servi par islamicapi.com. */
  audio: string;
}

export const NAMES_99: Name99[] = [
  { transliteration: "Ar-Rahman", arabic: "الرحمن", translation: "Le Tout Miséricordieux", description: "Celui dont la miséricorde est immense et englobe toute la création.", audio: 'https://islamicapi.com/audio/asma-ul-husna/rahman.mp3' },
  { transliteration: "Ar-Rahim", arabic: "الرحيم", translation: "Le Très Miséricordieux", description: "Celui dont la miséricorde se manifeste spécialement pour les croyants.", audio: 'https://islamicapi.com/audio/asma-ul-husna/rahim.mp3' },
  { transliteration: "Al-Malik", arabic: "الملك", translation: "Le Roi absolu", description: "Le Seigneur de tous les royaumes, à qui appartient toute autorité.", audio: 'https://islamicapi.com/audio/asma-ul-husna/malik.mp3' },
  { transliteration: "Al-Quddus", arabic: "القدوس", translation: "Le Saint", description: "Le pur, exempt de tout défaut, sanctifié au-delà de toute imperfection.", audio: 'https://islamicapi.com/audio/asma-ul-husna/quddus.mp3' },
  { transliteration: "As-Salam", arabic: "السلام", translation: "Le Donateur de paix", description: "Celui qui accorde la paix intérieure et la sécurité à Ses serviteurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/salam.mp3' },
  { transliteration: "Al-Mu'min", arabic: "المؤمن", translation: "Le Gardien de la foi", description: "Celui qui protège les croyants et accorde la sécurité.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mumin.mp3' },
  { transliteration: "Al-Muhaymin", arabic: "المهيمن", translation: "Le Protecteur", description: "Celui qui surveille, protège et vérifie toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muhaimin.mp3' },
  { transliteration: "Al-'Aziz", arabic: "العزيز", translation: "Le Tout-Puissant", description: "Le Fort, dont la puissance ne peut être vaincue.", audio: 'https://islamicapi.com/audio/asma-ul-husna/aziz.mp3' },
  { transliteration: "Al-Jabbar", arabic: "الجبار", translation: "Le Redresseur", description: "Celui qui rétablit l'ordre et guérit les cœurs brisés.", audio: 'https://islamicapi.com/audio/asma-ul-husna/jabbar.mp3' },
  { transliteration: "Al-Mutakabbir", arabic: "المتكبر", translation: "Le Suprême", description: "Celui qui Se glorifie avec justice, au-dessus de toute arrogance créée.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mutakabbir.mp3' },
  { transliteration: "Al-Khaliq", arabic: "الخالق", translation: "Le Créateur", description: "Celui qui fait exister toute chose à partir du néant.", audio: 'https://islamicapi.com/audio/asma-ul-husna/khaliq.mp3' },
  { transliteration: "Al-Bari'", arabic: "البارئ", translation: "Le Donateur de forme", description: "Celui qui modèle les créations avec perfection.", audio: 'https://islamicapi.com/audio/asma-ul-husna/bari.mp3' },
  { transliteration: "Al-Musawwir", arabic: "المصور", translation: "Le Façonneur", description: "Celui qui donne à chaque créature sa forme et sa beauté.", audio: 'https://islamicapi.com/audio/asma-ul-husna/musawwir.mp3' },
  { transliteration: "Al-Ghaffar", arabic: "الغفار", translation: "Le Grand Pardonneur", description: "Celui qui pardonne les péchés, même répétés, à Ses serviteurs repentants.", audio: 'https://islamicapi.com/audio/asma-ul-husna/ghaffar.mp3' },
  { transliteration: "Al-Qahhar", arabic: "القهار", translation: "Le Dominateur absolu", description: "Celui qui soumet toute chose par Sa puissance.", audio: 'https://islamicapi.com/audio/asma-ul-husna/qahhar.mp3' },
  { transliteration: "Al-Wahhab", arabic: "الوهاب", translation: "Le Donateur généreux", description: "Celui qui accorde Ses dons sans compter.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wahhab.mp3' },
  { transliteration: "Ar-Razzaq", arabic: "الرزاق", translation: "Le Pourvoyeur", description: "Celui qui nourrit toute la création, chaque créature selon son besoin.", audio: 'https://islamicapi.com/audio/asma-ul-husna/razzaq.mp3' },
  { transliteration: "Al-Fattah", arabic: "الفتاح", translation: "L'Ouvreur", description: "Celui qui ouvre les portes de la miséricorde et du savoir.", audio: 'https://islamicapi.com/audio/asma-ul-husna/fattah.mp3' },
  { transliteration: "Al-Alim", arabic: "العليم", translation: "Le Très-Savant", description: "Celui qui sait tout, le passé, le présent et le futur.", audio: 'https://islamicapi.com/audio/asma-ul-husna/alim.mp3' },
  { transliteration: "Al-Qabid", arabic: "القابض", translation: "Le Contracteur", description: "Celui qui resserre et retient ce qu'Il veut.", audio: 'https://islamicapi.com/audio/asma-ul-husna/qabid.mp3' },
  { transliteration: "Al-Basit", arabic: "الباسط", translation: "L'Étendant", description: "Celui qui étend Sa miséricorde et Ses bienfaits.", audio: 'https://islamicapi.com/audio/asma-ul-husna/basit.mp3' },
  { transliteration: "Al-Khafid", arabic: "الخافض", translation: "L'Abaisseur", description: "Celui qui abaisse l'orgueilleux et élève les humbles.", audio: 'https://islamicapi.com/audio/asma-ul-husna/khafid.mp3' },
  { transliteration: "Ar-Rafi'", arabic: "الرافع", translation: "L'Élévateur", description: "Celui qui élève les croyants en dignité et en rang.", audio: 'https://islamicapi.com/audio/asma-ul-husna/rafi.mp3' },
  { transliteration: "Al-Mu'izz", arabic: "المعز", translation: "Le Donateur d'honneur", description: "Celui qui accorde la noblesse et l'honneur.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muizz.mp3' },
  { transliteration: "Al-Mudhill", arabic: "المذل", translation: "L'Humiliateur", description: "Celui qui humilie les injustes et les oppresseurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mudhill.mp3' },
  { transliteration: "As-Sami'", arabic: "السميع", translation: "L'Auditeur parfait", description: "Celui qui entend toute chose, même le murmure du cœur.", audio: 'https://islamicapi.com/audio/asma-ul-husna/sami.mp3' },
  { transliteration: "Al-Baseer", arabic: "البصير", translation: "Le Clairvoyant", description: "Celui qui voit tout, même les intentions cachées.", audio: 'https://islamicapi.com/audio/asma-ul-husna/basir.mp3' },
  { transliteration: "Al-Hakam", arabic: "الحكم", translation: "Le Juge suprême", description: "Celui qui juge entre Ses serviteurs avec justice absolue.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hakam.mp3' },
  { transliteration: "Al-Adl", arabic: "العدل", translation: "Le Juste", description: "Celui qui ne commet aucune injustice, même du poids d'un atome.", audio: 'https://islamicapi.com/audio/asma-ul-husna/adl.mp3' },
  { transliteration: "Al-Latif", arabic: "اللطيف", translation: "Le Subtil", description: "Celui qui connaît les besoins secrets de Ses serviteurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/latif.mp3' },
  { transliteration: "Al-Khabir", arabic: "الخبير", translation: "L'Expert", description: "Celui qui a une connaissance parfaite de toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/khabir.mp3' },
  { transliteration: "Al-Halim", arabic: "الحليم", translation: "Le Longanime", description: "Celui qui ne se précipite pas pour punir, qui pardonne.", audio: 'https://islamicapi.com/audio/asma-ul-husna/halim.mp3' },
  { transliteration: "Al-'Azim", arabic: "العظيم", translation: "Le Grand", description: "Celui dont la grandeur est infinie, au-delà de toute description.", audio: 'https://islamicapi.com/audio/asma-ul-husna/azim.mp3' },
  { transliteration: "Al-Ghafur", arabic: "الغفور", translation: "Le Très Pardonneur", description: "Celui qui pardonne abondamment les péchés de Ses serviteurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/ghafur.mp3' },
  { transliteration: "Ash-Shakur", arabic: "الشكور", translation: "Le Reconnaissant", description: "Celui qui récompense même le moindre acte de bien.", audio: 'https://islamicapi.com/audio/asma-ul-husna/shakur.mp3' },
  { transliteration: "Al-'Aliyy", arabic: "العلي", translation: "Le Très-Haut", description: "Le plus élevé en dignité, en majesté et en science.", audio: 'https://islamicapi.com/audio/asma-ul-husna/ali.mp3' },
  { transliteration: "Al-Kabir", arabic: "الكبير", translation: "Le Très Grand", description: "Le grand en toute chose, Sa grandeur est incomparable.", audio: 'https://islamicapi.com/audio/asma-ul-husna/kabir.mp3' },
  { transliteration: "Al-Hafiz", arabic: "الحفيظ", translation: "Le Gardien vigilant", description: "Celui qui préserve et protège toute chose sous Sa garde.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hafiz.mp3' },
  { transliteration: "Al-Muqit", arabic: "المقيت", translation: "Le Seigneur de la sustentation", description: "Celui qui administre les subsistances de Ses créatures.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muqit.mp3' },
  { transliteration: "Al-Hasib", arabic: "الحسيب", translation: "Le Puissant en autorité", description: "Celui qui suffit à Ses serviteurs et qui rend compte.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hasib.mp3' },
  { transliteration: "Al-Jalil", arabic: "الجليل", translation: "Le Majestueux", description: "Celui dont la majesté inspire le respect et la crainte.", audio: 'https://islamicapi.com/audio/asma-ul-husna/jalil.mp3' },
  { transliteration: "Al-Karim", arabic: "الكريم", translation: "Le Généreux", description: "Le plus noble, le plus généreux en dons et en honneurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/karim.mp3' },
  { transliteration: "Ar-Raqib", arabic: "الرقيب", translation: "Le Vigilant", description: "Celui qui entend sans effort et surveille sans cesse Ses créatures.", audio: 'https://islamicapi.com/audio/asma-ul-husna/raqib.mp3' },
  { transliteration: "Al-Mujib", arabic: "المجيب", translation: "L'Exauçant", description: "Celui qui répond à chaque invocation, même celle du cœur.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mujib.mp3' },
  { transliteration: "Al-Wasi'", arabic: "الواسع", translation: "L'Immense", description: "L'immensité de Sa miséricorde et de Sa science n'a pas de limites.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wasi.mp3' },
  { transliteration: "Al-Hakim", arabic: "الحكيم", translation: "Le Sage", description: "Celui dont la sagesse guide toutes les décisions.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hakim.mp3' },
  { transliteration: "Al-Wadud", arabic: "الودود", translation: "Le Bien-Aimant", description: "Celui qui aime Ses serviteurs vertueux et qui est aimé par eux.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wadud.mp3' },
  { transliteration: "Al-Majid", arabic: "المجيد", translation: "Le Glorieux", description: "Celui dont la noblesse et la générosité sont infinies.", audio: 'https://islamicapi.com/audio/asma-ul-husna/majeed.mp3' },
  { transliteration: "Al-Ba'ith", arabic: "الباعث", translation: "Le Ressusciteur", description: "Celui qui ressuscitera les morts le Jour du Jugement.", audio: 'https://islamicapi.com/audio/asma-ul-husna/baith.mp3' },
  { transliteration: "Ash-Shahid", arabic: "الشهيد", translation: "Le Témoin parfait", description: "Celui qui voit tout sans être vu, le témoin universel.", audio: 'https://islamicapi.com/audio/asma-ul-husna/shahid.mp3' },
  { transliteration: "Al-Haqq", arabic: "الحق", translation: "Le Véritable", description: "La vérité absolue, dont tout dépend.", audio: 'https://islamicapi.com/audio/asma-ul-husna/haqq.mp3' },
  { transliteration: "Al-Wakil", arabic: "الوكيل", translation: "Le Garant", description: "Le protecteur et le tuteur de Ses serviteurs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wakil.mp3' },
  { transliteration: "Al-Qawiyy", arabic: "القوي", translation: "Le Fort", description: "La force qui maintient les cieux et la terre.", audio: 'https://islamicapi.com/audio/asma-ul-husna/qawi.mp3' },
  { transliteration: "Al-Matin", arabic: "المتين", translation: "L'Inébranlable", description: "La solidité parfaite, qui ne fléchit jamais.", audio: 'https://islamicapi.com/audio/asma-ul-husna/matin.mp3' },
  { transliteration: "Al-Waliyy", arabic: "الولي", translation: "Le Protecteur", description: "L'ami proche, le protecteur des croyants.", audio: 'https://islamicapi.com/audio/asma-ul-husna/waliy.mp3' },
  { transliteration: "Al-Hamid", arabic: "الحميد", translation: "Le Digne de louange", description: "Celui qui mérite toute louange par Ses œuvres parfaites.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hamid.mp3' },
  { transliteration: "Al-Muhsi", arabic: "المحصي", translation: "Le Recenseur", description: "Celui qui dénombre toute chose, dont le savoir embrasse chaque détail.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muhsi.mp3' },
  { transliteration: "Al-Mubdi'", arabic: "المبدئ", translation: "L'Initiateur", description: "Celui qui commence la création sans modèle préalable.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mubdi.mp3' },
  { transliteration: "Al-Mu'id", arabic: "المعيد", translation: "Le Restaurateur", description: "Celui qui répète et ramène la création après l'avoir fait naître.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muid.mp3' },
  { transliteration: "Al-Muhyi", arabic: "المحيي", translation: "Le Vivificateur", description: "Celui qui donne la vie à toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muhyi.mp3' },
  { transliteration: "Al-Mumit", arabic: "المميت", translation: "L'Octroyeur de la mort", description: "Celui qui fait mourir toute créature au moment fixé.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mumit.mp3' },
  { transliteration: "Al-Hayy", arabic: "الحي", translation: "Le Vivant", description: "Celui dont la vie est éternelle, sans début ni fin.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hayy.mp3' },
  { transliteration: "Al-Qayyum", arabic: "القيوم", translation: "Le Subsistant par Lui-même", description: "Celui qui subsiste par Lui-même et fait subsister toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/qayyum.mp3' },
  { transliteration: "Al-Wajid", arabic: "الواجد", translation: "Le Riche", description: "Celui qui ne manque de rien et trouve toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wajid.mp3' },
  { transliteration: "Al-Majid", arabic: "الماجد", translation: "Le Magnifique", description: "Celui dont la gloire et la générosité sont immenses.", audio: 'https://islamicapi.com/audio/asma-ul-husna/majid.mp3' },
  { transliteration: "Al-Wahid", arabic: "الواحد", translation: "L'Unique", description: "Celui qui est unique dans Son essence et Ses attributs.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wahid.mp3' },
  { transliteration: "Al-Ahad", arabic: "الاحد", translation: "L'Un", description: "Celui qui est Un, sans associé ni semblable.", audio: 'https://islamicapi.com/audio/asma-ul-husna/ahad.mp3' },
  { transliteration: "As-Samad", arabic: "الصمد", translation: "L'Éternel Refuge", description: "Celui vers qui on se tourne dans le besoin, qui n'a besoin de personne.", audio: 'https://islamicapi.com/audio/asma-ul-husna/samad.mp3' },
  { transliteration: "Al-Qadir", arabic: "القادر", translation: "Le Capable", description: "Celui dont le pouvoir s'étend sur toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/qadir.mp3' },
  { transliteration: "Al-Muqtadir", arabic: "المقتدر", translation: "Le Tout-Déterminant", description: "Celui qui dispose de tout selon Sa volonté.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muqtadir.mp3' },
  { transliteration: "Al-Muqaddim", arabic: "المقدم", translation: "Le Promoteur", description: "Celui qui avance et élève qui Il veut.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muqaddim.mp3' },
  { transliteration: "Al-Mu'akhkhir", arabic: "المؤخر", translation: "Le Repousseur", description: "Celui qui retarde et abaisse qui Il veut.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muakhkhir.mp3' },
  { transliteration: "Al-Awwal", arabic: "الاول", translation: "Le Premier", description: "Celui qui existe avant toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/awwal.mp3' },
  { transliteration: "Al-Akhir", arabic: "الاخر", translation: "Le Dernier", description: "Celui qui subsiste après toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/akhir.mp3' },
  { transliteration: "Az-Zahir", arabic: "الظاهر", translation: "Le Manifeste", description: "Celui dont l'existence est évidente par Ses signes.", audio: 'https://islamicapi.com/audio/asma-ul-husna/zahir.mp3' },
  { transliteration: "Al-Batin", arabic: "الباطن", translation: "Le Caché", description: "Celui qui échappe aux regards mais est proche de toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/batin.mp3' },
  { transliteration: "Al-Wali", arabic: "الوالي", translation: "Le Gouverneur", description: "Celui qui gouverne toute chose avec sagesse.", audio: 'https://islamicapi.com/audio/asma-ul-husna/wali.mp3' },
  { transliteration: "Al-Muta'ali", arabic: "المتعالي", translation: "Le Très-Haut", description: "Celui qui est au-dessus de toute imperfection, exalté.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muta_ali.mp3' },
  { transliteration: "Al-Barr", arabic: "البر", translation: "La Source de toute bonté", description: "Celui dont la bonté embrasse toutes Ses créatures.", audio: 'https://islamicapi.com/audio/asma-ul-husna/barr.mp3' },
  { transliteration: "At-Tawwab", arabic: "التواب", translation: "L'Accueillant au repentir", description: "Celui qui accepte le repentir et le renouvelle.", audio: 'https://islamicapi.com/audio/asma-ul-husna/tawwab.mp3' },
  { transliteration: "Al-Muntaqim", arabic: "المنتقم", translation: "Le Vengeur", description: "Celui qui punit avec justice ceux qui persistent dans l'injustice.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muntaqim.mp3' },
  { transliteration: "Al-'Afuww", arabic: "العفو", translation: "Le Pardonneur", description: "Celui qui efface les péchés sans en garder trace.", audio: 'https://islamicapi.com/audio/asma-ul-husna/afuw.mp3' },
  { transliteration: "Ar-Ra'uf", arabic: "الرؤوف", translation: "Le Très Clément", description: "Celui dont la clémence est plus grande encore que Sa miséricorde.", audio: 'https://islamicapi.com/audio/asma-ul-husna/rauf.mp3' },
  { transliteration: "Malik-ul-Mulk", arabic: "مالك الملك", translation: "Le Souverain du royaume", description: "Le Maître absolu de toute royauté et de tout pouvoir.", audio: 'https://islamicapi.com/audio/asma-ul-husna/malik_ul_mulk.mp3' },
  { transliteration: "Dhu-l-Jalali wa-l-Ikram", arabic: "ذو الجلال والاكرام", translation: "Le Détenteur de la majesté et de la générosité", description: "Celui qui mérite la glorification et l'honneur.", audio: 'https://islamicapi.com/audio/asma-ul-husna/dhu_l_jalali_wal_ikram.mp3' },
  { transliteration: "Al-Muqsit", arabic: "المقسط", translation: "L'Équitable", description: "Celui qui rend justice avec une équité parfaite.", audio: 'https://islamicapi.com/audio/asma-ul-husna/muqsit.mp3' },
  { transliteration: "Al-Jami'", arabic: "الجامع", translation: "Le Rassembleur", description: "Celui qui rassemble les créatures au Jour du Jugement.", audio: 'https://islamicapi.com/audio/asma-ul-husna/jami.mp3' },
  { transliteration: "Al-Ghaniyy", arabic: "الغني", translation: "Le Riche", description: "Celui qui se suffit à Lui-même et n'a besoin de rien.", audio: 'https://islamicapi.com/audio/asma-ul-husna/ghaniy.mp3' },
  { transliteration: "Al-Mughni", arabic: "المغني", translation: "L'Enrichisseur", description: "Celui qui accorde la richesse et comble les besoins.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mughni.mp3' },
  { transliteration: "Al-Mani'", arabic: "المانع", translation: "Le Défenseur", description: "Celui qui retient et protège qui Il veut.", audio: 'https://islamicapi.com/audio/asma-ul-husna/mani.mp3' },
  { transliteration: "Ad-Darr", arabic: "الضار", translation: "Le Bienfaisant par l'épreuve", description: "Celui qui peut éprouver pour purifier et rappeler.", audio: 'https://islamicapi.com/audio/asma-ul-husna/darr.mp3' },
  { transliteration: "An-Nafi'", arabic: "النافع", translation: "Le Bienfaisant", description: "Celui qui accorde tous les bienfaits.", audio: 'https://islamicapi.com/audio/asma-ul-husna/nafi.mp3' },
  { transliteration: "An-Nur", arabic: "النور", translation: "La Lumière", description: "La lumière qui éclaire les cieux et la terre.", audio: 'https://islamicapi.com/audio/asma-ul-husna/nur.mp3' },
  { transliteration: "Al-Hadi", arabic: "الهادي", translation: "Le Guide", description: "Celui qui guide vers le droit chemin.", audio: 'https://islamicapi.com/audio/asma-ul-husna/hadi.mp3' },
  { transliteration: "Al-Badi'", arabic: "البديع", translation: "L'Inventeur", description: "Celui qui crée de façon unique et sans modèle.", audio: 'https://islamicapi.com/audio/asma-ul-husna/badi.mp3' },
  { transliteration: "Al-Baqi", arabic: "الباقي", translation: "L'Éternel", description: "Celui qui demeure à jamais.", audio: 'https://islamicapi.com/audio/asma-ul-husna/baqi.mp3' },
  { transliteration: "Al-Warith", arabic: "الوارث", translation: "L'Héritier", description: "Celui qui hérite de toute chose.", audio: 'https://islamicapi.com/audio/asma-ul-husna/warith.mp3' },
  { transliteration: "Ar-Rashid", arabic: "الرشيد", translation: "Le Bien-Guidé", description: "Celui dont la guidance est parfaite.", audio: 'https://islamicapi.com/audio/asma-ul-husna/rashid.mp3' },
  { transliteration: "As-Sabur", arabic: "الصبور", translation: "Le Très Patient", description: "Celui dont la patience est infinie.", audio: 'https://islamicapi.com/audio/asma-ul-husna/sabur.mp3' },
];
