export interface SurahMeta {
  number: number;
  arabic: string;
  name: string;
  english: string;
  ayahs: number;
  revelation: 'Meccan' | 'Medinan';
}

export const SURAHS: SurahMeta[] = [
  { number: 1, arabic: 'الفاتحة', name: 'Al-Fatiha', english: 'The Opening', ayahs: 7, revelation: 'Meccan' },
  { number: 2, arabic: 'البقرة', name: 'Al-Baqara', english: 'The Cow', ayahs: 286, revelation: 'Medinan' },
  { number: 3, arabic: 'آل عمران', name: "Ali 'Imran", english: 'Family of Imran', ayahs: 200, revelation: 'Medinan' },
  { number: 4, arabic: 'النساء', name: 'An-Nisa', english: 'The Women', ayahs: 176, revelation: 'Medinan' },
  { number: 5, arabic: 'المائدة', name: 'Al-Maidah', english: 'The Table Spread', ayahs: 120, revelation: 'Medinan' },
  { number: 6, arabic: 'الأنعام', name: "Al-An'am", english: 'The Cattle', ayahs: 165, revelation: 'Meccan' },
  { number: 7, arabic: 'الأعراف', name: "Al-A'raf", english: 'The Heights', ayahs: 206, revelation: 'Meccan' },
  { number: 8, arabic: 'الأنفال', name: 'Al-Anfal', english: 'The Spoils of War', ayahs: 75, revelation: 'Medinan' },
  { number: 9, arabic: 'التوبة', name: 'At-Tawbah', english: 'The Repentance', ayahs: 129, revelation: 'Medinan' },
  { number: 10, arabic: 'يونس', name: 'Yunus', english: 'Jonah', ayahs: 109, revelation: 'Meccan' },
  { number: 11, arabic: 'هود', name: 'Hud', english: 'Hud', ayahs: 123, revelation: 'Meccan' },
  { number: 12, arabic: 'يوسف', name: 'Yusuf', english: 'Joseph', ayahs: 111, revelation: 'Meccan' },
  { number: 13, arabic: 'الرعد', name: "Ar-Ra'd", english: 'Thunder', ayahs: 43, revelation: 'Medinan' },
  { number: 14, arabic: 'إبراهيم', name: 'Ibrahim', english: 'Abraham', ayahs: 52, revelation: 'Meccan' },
  { number: 15, arabic: 'الحجر', name: 'Al-Hijr', english: 'The Rocky Tract', ayahs: 99, revelation: 'Meccan' },
  { number: 16, arabic: 'النحل', name: 'An-Nahl', english: 'The Bee', ayahs: 128, revelation: 'Meccan' },
  { number: 17, arabic: 'الإسراء', name: 'Al-Isra', english: 'The Night Journey', ayahs: 111, revelation: 'Meccan' },
  { number: 18, arabic: 'الكهف', name: 'Al-Kahf', english: 'The Cave', ayahs: 110, revelation: 'Meccan' },
  { number: 19, arabic: 'مريم', name: 'Maryam', english: 'Mary', ayahs: 98, revelation: 'Meccan' },
  { number: 20, arabic: 'طه', name: 'Ta-Ha', english: 'Ta-Ha', ayahs: 135, revelation: 'Meccan' },
  { number: 21, arabic: 'الأنبياء', name: 'Al-Anbiya', english: 'The Prophets', ayahs: 112, revelation: 'Meccan' },
  { number: 22, arabic: 'الحج', name: 'Al-Hajj', english: 'The Pilgrimage', ayahs: 78, revelation: 'Medinan' },
  { number: 23, arabic: 'المؤمنون', name: 'Al-Muminun', english: 'The Believers', ayahs: 118, revelation: 'Meccan' },
  { number: 24, arabic: 'النور', name: 'An-Nur', english: 'The Light', ayahs: 64, revelation: 'Medinan' },
  { number: 25, arabic: 'الفرقان', name: 'Al-Furqan', english: 'The Criterion', ayahs: 77, revelation: 'Meccan' },
  { number: 26, arabic: 'الشعراء', name: "Ash-Shu'ara", english: 'The Poets', ayahs: 227, revelation: 'Meccan' },
  { number: 27, arabic: 'النمل', name: 'An-Naml', english: 'The Ants', ayahs: 93, revelation: 'Meccan' },
  { number: 28, arabic: 'القصص', name: 'Al-Qasas', english: 'The Stories', ayahs: 88, revelation: 'Meccan' },
  { number: 29, arabic: 'العنكبوت', name: 'Al-Ankabut', english: 'The Spider', ayahs: 69, revelation: 'Meccan' },
  { number: 30, arabic: 'الروم', name: 'Ar-Rum', english: 'The Romans', ayahs: 60, revelation: 'Meccan' },
  { number: 31, arabic: 'لقمان', name: 'Luqman', english: 'Luqman', ayahs: 34, revelation: 'Meccan' },
  { number: 32, arabic: 'السجدة', name: 'As-Sajdah', english: 'The Prostration', ayahs: 30, revelation: 'Meccan' },
  { number: 33, arabic: 'الأحزاب', name: 'Al-Ahzab', english: 'The Confederates', ayahs: 73, revelation: 'Medinan' },
  { number: 34, arabic: 'سبأ', name: 'Saba', english: 'Sheba', ayahs: 54, revelation: 'Meccan' },
  { number: 35, arabic: 'فاطر', name: 'Fatir', english: 'The Originator', ayahs: 45, revelation: 'Meccan' },
  { number: 36, arabic: 'يس', name: 'Ya-Sin', english: 'Ya-Sin', ayahs: 83, revelation: 'Meccan' },
  { number: 37, arabic: 'الصافات', name: 'As-Saffat', english: 'Those Drawn Up', ayahs: 182, revelation: 'Meccan' },
  { number: 38, arabic: 'ص', name: 'Sad', english: 'Sad', ayahs: 88, revelation: 'Meccan' },
  { number: 39, arabic: 'الزمر', name: 'Az-Zumar', english: 'The Troops', ayahs: 75, revelation: 'Meccan' },
  { number: 40, arabic: 'غافر', name: 'Ghafir', english: 'The Forgiver', ayahs: 85, revelation: 'Meccan' },
  { number: 41, arabic: 'فصلت', name: 'Fussilat', english: 'Explained In Detail', ayahs: 54, revelation: 'Meccan' },
  { number: 42, arabic: 'الشورى', name: 'Ash-Shura', english: 'The Consultation', ayahs: 53, revelation: 'Meccan' },
  { number: 43, arabic: 'الزخرف', name: 'Az-Zukhruf', english: 'The Ornaments', ayahs: 89, revelation: 'Meccan' },
  { number: 44, arabic: 'الدخان', name: 'Ad-Dukhan', english: 'The Smoke', ayahs: 59, revelation: 'Meccan' },
  { number: 45, arabic: 'الجاثية', name: 'Al-Jathiyah', english: 'The Kneeling', ayahs: 37, revelation: 'Meccan' },
  { number: 46, arabic: 'الأحقاف', name: 'Al-Ahqaf', english: 'The Dunes', ayahs: 35, revelation: 'Meccan' },
  { number: 47, arabic: 'محمد', name: 'Muhammad', english: 'Muhammad', ayahs: 38, revelation: 'Medinan' },
  { number: 48, arabic: 'الفتح', name: 'Al-Fath', english: 'The Victory', ayahs: 29, revelation: 'Medinan' },
  { number: 49, arabic: 'الحجرات', name: 'Al-Hujurat', english: 'The Chambers', ayahs: 18, revelation: 'Medinan' },
  { number: 50, arabic: 'ق', name: 'Qaf', english: 'Qaf', ayahs: 45, revelation: 'Meccan' },
  { number: 51, arabic: 'الذاريات', name: 'Adh-Dhariyat', english: 'The Scatterers', ayahs: 60, revelation: 'Meccan' },
  { number: 52, arabic: 'الطور', name: 'At-Tur', english: 'The Mount', ayahs: 49, revelation: 'Meccan' },
  { number: 53, arabic: 'النجم', name: 'An-Najm', english: 'The Star', ayahs: 62, revelation: 'Meccan' },
  { number: 54, arabic: 'القمر', name: 'Al-Qamar', english: 'The Moon', ayahs: 55, revelation: 'Meccan' },
  { number: 55, arabic: 'الرحمن', name: 'Ar-Rahman', english: 'The Most Merciful', ayahs: 78, revelation: 'Medinan' },
  { number: 56, arabic: 'الواقعة', name: "Al-Waqi'ah", english: 'The Inevitable', ayahs: 96, revelation: 'Meccan' },
  { number: 57, arabic: 'الحديد', name: 'Al-Hadid', english: 'Iron', ayahs: 29, revelation: 'Medinan' },
  { number: 58, arabic: 'المجادلة', name: 'Al-Mujadilah', english: 'The Pleading Woman', ayahs: 22, revelation: 'Medinan' },
  { number: 59, arabic: 'الحشر', name: 'Al-Hashr', english: 'The Exile', ayahs: 24, revelation: 'Medinan' },
  { number: 60, arabic: 'الممتحنة', name: 'Al-Mumtahanah', english: 'She Tested', ayahs: 13, revelation: 'Medinan' },
  { number: 61, arabic: 'الصف', name: 'As-Saff', english: 'The Ranks', ayahs: 14, revelation: 'Medinan' },
  { number: 62, arabic: 'الجمعة', name: "Al-Jumu'ah", english: 'Friday', ayahs: 11, revelation: 'Medinan' },
  { number: 63, arabic: 'المنافقون', name: 'Al-Munafiqun', english: 'The Hypocrites', ayahs: 11, revelation: 'Medinan' },
  { number: 64, arabic: 'التغابن', name: 'At-Taghabun', english: 'Mutual Dispossession', ayahs: 18, revelation: 'Medinan' },
  { number: 65, arabic: 'الطلاق', name: 'At-Talaq', english: 'The Divorce', ayahs: 12, revelation: 'Medinan' },
  { number: 66, arabic: 'التحريم', name: 'At-Tahrim', english: 'The Prohibition', ayahs: 12, revelation: 'Medinan' },
  { number: 67, arabic: 'الملك', name: 'Al-Mulk', english: 'The Sovereignty', ayahs: 30, revelation: 'Meccan' },
  { number: 68, arabic: 'القلم', name: 'Al-Qalam', english: 'The Pen', ayahs: 52, revelation: 'Meccan' },
  { number: 69, arabic: 'الحاقة', name: 'Al-Haqqah', english: 'The Reality', ayahs: 52, revelation: 'Meccan' },
  { number: 70, arabic: 'المعارج', name: "Al-Ma'arij", english: 'The Ascending Stairways', ayahs: 44, revelation: 'Meccan' },
  { number: 71, arabic: 'نوح', name: 'Nuh', english: 'Noah', ayahs: 28, revelation: 'Meccan' },
  { number: 72, arabic: 'الجن', name: 'Al-Jinn', english: 'The Jinn', ayahs: 28, revelation: 'Meccan' },
  { number: 73, arabic: 'المزمل', name: 'Al-Muzzammil', english: 'The Enwrapped One', ayahs: 20, revelation: 'Meccan' },
  { number: 74, arabic: 'المدثر', name: 'Al-Muddaththir', english: 'The Cloaked One', ayahs: 56, revelation: 'Meccan' },
  { number: 75, arabic: 'القيامة', name: 'Al-Qiyamah', english: 'The Resurrection', ayahs: 40, revelation: 'Meccan' },
  { number: 76, arabic: 'الإنسان', name: 'Al-Insan', english: 'Man', ayahs: 31, revelation: 'Medinan' },
  { number: 77, arabic: 'المرسلات', name: 'Al-Mursalat', english: 'Those Sent Forth', ayahs: 50, revelation: 'Meccan' },
  { number: 78, arabic: 'النبأ', name: 'An-Naba', english: 'The Tidings', ayahs: 40, revelation: 'Meccan' },
  { number: 79, arabic: 'النازعات', name: "An-Nazi'at", english: 'Those Who Drag Forth', ayahs: 46, revelation: 'Meccan' },
  { number: 80, arabic: 'عبس', name: 'Abasa', english: 'He Frowned', ayahs: 42, revelation: 'Meccan' },
  { number: 81, arabic: 'التكوير', name: 'At-Takwir', english: 'The Overthrowing', ayahs: 29, revelation: 'Meccan' },
  { number: 82, arabic: 'الانفطار', name: 'Al-Infitar', english: 'The Cleaving', ayahs: 19, revelation: 'Meccan' },
  { number: 83, arabic: 'المطففين', name: 'Al-Mutaffifin', english: 'The Defrauders', ayahs: 36, revelation: 'Meccan' },
  { number: 84, arabic: 'الانشقاق', name: 'Al-Inshiqaq', english: 'The Splitting Open', ayahs: 25, revelation: 'Meccan' },
  { number: 85, arabic: 'البروج', name: 'Al-Buruj', english: 'The Constellations', ayahs: 22, revelation: 'Meccan' },
  { number: 86, arabic: 'الطارق', name: 'At-Tariq', english: 'The Nightcomer', ayahs: 17, revelation: 'Meccan' },
  { number: 87, arabic: 'الأعلى', name: "Al-A'la", english: 'The Most High', ayahs: 19, revelation: 'Meccan' },
  { number: 88, arabic: 'الغاشية', name: 'Al-Ghashiyah', english: 'The Overwhelming Event', ayahs: 26, revelation: 'Meccan' },
  { number: 89, arabic: 'الفجر', name: 'Al-Fajr', english: 'The Dawn', ayahs: 30, revelation: 'Meccan' },
  { number: 90, arabic: 'البلد', name: 'Al-Balad', english: 'The City', ayahs: 20, revelation: 'Meccan' },
  { number: 91, arabic: 'الشمس', name: 'Ash-Shams', english: 'The Sun', ayahs: 15, revelation: 'Meccan' },
  { number: 92, arabic: 'الليل', name: 'Al-Layl', english: 'The Night', ayahs: 21, revelation: 'Meccan' },
  { number: 93, arabic: 'الضحى', name: 'Ad-Duha', english: 'The Morning Hours', ayahs: 11, revelation: 'Meccan' },
  { number: 94, arabic: 'الشرح', name: 'Ash-Sharh', english: 'The Relief', ayahs: 8, revelation: 'Meccan' },
  { number: 95, arabic: 'التين', name: 'At-Tin', english: 'The Fig', ayahs: 8, revelation: 'Meccan' },
  { number: 96, arabic: 'العلق', name: 'Al-Alaq', english: 'The Clot', ayahs: 19, revelation: 'Meccan' },
  { number: 97, arabic: 'القدر', name: 'Al-Qadr', english: 'The Power', ayahs: 5, revelation: 'Meccan' },
  { number: 98, arabic: 'البينة', name: 'Al-Bayyinah', english: 'The Clear Evidence', ayahs: 8, revelation: 'Medinan' },
  { number: 99, arabic: 'الزلزلة', name: 'Az-Zalzalah', english: 'The Earthquake', ayahs: 8, revelation: 'Medinan' },
  { number: 100, arabic: 'العاديات', name: 'Al-Adiyat', english: 'The Coursers', ayahs: 11, revelation: 'Meccan' },
  { number: 101, arabic: 'القارعة', name: "Al-Qari'ah", english: 'The Calamity', ayahs: 11, revelation: 'Meccan' },
  { number: 102, arabic: 'التكاثر', name: 'At-Takathur', english: 'The Rivalry in Increase', ayahs: 8, revelation: 'Meccan' },
  { number: 103, arabic: 'العصر', name: 'Al-Asr', english: 'The Declining Day', ayahs: 3, revelation: 'Meccan' },
  { number: 104, arabic: 'الهمزة', name: 'Al-Humazah', english: 'The Slanderer', ayahs: 9, revelation: 'Meccan' },
  { number: 105, arabic: 'الفيل', name: 'Al-Fil', english: 'The Elephant', ayahs: 5, revelation: 'Meccan' },
  { number: 106, arabic: 'قريش', name: 'Quraysh', english: 'Quraysh', ayahs: 4, revelation: 'Meccan' },
  { number: 107, arabic: 'الماعون', name: "Al-Ma'un", english: 'The Small Kindnesses', ayahs: 7, revelation: 'Meccan' },
  { number: 108, arabic: 'الكوثر', name: 'Al-Kawthar', english: 'The Abundance', ayahs: 3, revelation: 'Meccan' },
  { number: 109, arabic: 'الكافرون', name: 'Al-Kafirun', english: 'The Disbelievers', ayahs: 6, revelation: 'Meccan' },
  { number: 110, arabic: 'النصر', name: 'An-Nasr', english: 'The Help', ayahs: 3, revelation: 'Medinan' },
  { number: 111, arabic: 'المسد', name: 'Al-Masad', english: 'The Palm Fiber', ayahs: 5, revelation: 'Meccan' },
  { number: 112, arabic: 'الإخلاص', name: 'Al-Ikhlas', english: 'The Sincerity', ayahs: 4, revelation: 'Meccan' },
  { number: 113, arabic: 'الفلق', name: 'Al-Falaq', english: 'The Daybreak', ayahs: 5, revelation: 'Meccan' },
  { number: 114, arabic: 'الناس', name: 'An-Nas', english: 'Mankind', ayahs: 6, revelation: 'Meccan' },
];

export const FRENCH_NAMES: Record<number, string> = {
  1: "L'Ouverture",
  2: 'La Vache',
  3: "La Famille d'Imran",
  4: 'Les Femmes',
  5: 'La Table Servie',
  6: 'Les Bestiaux',
  7: 'Les Murailles',
  8: 'Le Butin',
  9: 'Le Repentir',
  10: 'Jonas',
  11: 'Hud',
  12: 'Joseph',
  13: 'Le Tonnerre',
  14: 'Abraham',
  15: 'Al-Hijr',
  16: 'Les Abeilles',
  17: 'Le Voyage Nocturne',
  18: 'La Caverne',
  19: 'Marie',
  20: 'Ta-Ha',
  21: 'Les Prophètes',
  22: 'Le Pèlerinage',
  23: 'Les Croyants',
  24: 'La Lumière',
  25: 'Le Discernement',
  26: 'Les Poètes',
  27: 'Les Fourmis',
  28: 'Le Récit',
  29: "L'Araignée",
  30: 'Les Romains',
  31: 'Luqman',
  32: 'La Prosternation',
  33: 'Les Coalisés',
  34: 'Saba',
  35: 'Le Créateur',
  36: 'Ya-Sin',
  37: 'Les Rangés',
  38: 'Sad',
  39: 'Les Groupes',
  40: 'Le Pardonneur',
  41: 'Les Versets Détaillés',
  42: 'La Concertation',
  43: "L'Ornement",
  44: 'La Fumée',
  45: "L'Agenouillée",
  46: 'Les Dunes',
  47: 'Muhammad',
  48: 'La Victoire',
  49: 'Les Appartements',
  50: 'Qaf',
  51: 'Les Éparpillées',
  52: 'Le Mont',
  53: "L'Étoile",
  54: 'La Lune',
  55: 'Le Tout Miséricordieux',
  56: "L'Événement",
  57: 'Le Fer',
  58: 'La Discussion',
  59: "L'Exode",
  60: "L'Éprouvée",
  61: 'Le Rang',
  62: 'Le Vendredi',
  63: 'Les Hypocrites',
  64: 'La Grande Perte',
  65: 'Le Divorce',
  66: "L'Interdiction",
  67: 'La Royauté',
  68: 'La Plume',
  69: "L'Inévitable",
  70: 'Les Voies Ascendantes',
  71: 'Noé',
  72: 'Les Djinns',
  73: "L'Enveloppé",
  74: 'Le Revêtu',
  75: 'La Résurrection',
  76: "L'Homme",
  77: 'Les Envoyées',
  78: 'La Nouvelle',
  79: 'Les Arracheurs',
  80: 'Il s\'est Renfrogné',
  81: "L'Obscurcissement",
  82: 'La Rupture',
  83: 'Les Fraudeurs',
  84: 'La Déchirure',
  85: 'Les Constellations',
  86: "L'Astre Nocturne",
  87: 'Le Très-Haut',
  88: "L'Enveloppante",
  89: "L'Aube",
  90: 'La Cité',
  91: 'Le Soleil',
  92: 'La Nuit',
  93: 'Le Jour Montant',
  94: "L'Ouverture",
  95: 'Le Figuier',
  96: "L'Adhérence",
  97: 'La Destinée',
  98: 'La Preuve',
  99: 'La Secousse',
  100: 'Les Coursiers',
  101: 'Le Fracas',
  102: 'La Course aux Richesses',
  103: 'Le Temps',
  104: 'Les Calomniateurs',
  105: "L'Éléphant",
  106: 'Quraysh',
  107: "L'Ustensile",
  108: "L'Abondance",
  109: 'Les Mécréants',
  110: 'Les Secours',
  111: 'Les Fibres',
  112: 'Le Monothéisme Pur',
  113: "L'Aube Naissante",
  114: 'Les Hommes',
};

export const KEYWORDS: Record<number, string[]> = {
  1: ['fatiha', 'ouverture', 'priere'],
  2: ['vache', 'baqara', 'ayat al kursi', 'trone', 'jeune', 'ramadan'],
  3: ['imran', 'famille', 'marie', 'jesus', 'issa'],
  4: ['femmes', 'nisa', 'mariage', 'heritage', 'orphelins'],
  5: ['table', 'maidah', 'nourriture', 'alliance', 'jesus'],
  6: ['bestiaux', 'anam', 'animaux', 'monotheisme'],
  7: ['murailles', 'araf', 'adam', 'paradis', 'enfer'],
  8: ['butin', 'anfal', 'guerre', 'badr'],
  9: ['repentir', 'tawba', 'guerre', 'tabuk'],
  10: ['jonas', 'younes', 'noe'],
  11: ['hud', 'aad', 'thamous'],
  12: ['joseph', 'yusuf', 'reve', 'egypte'],
  13: ['tonnerre', 'rad', 'eclair'],
  14: ['abraham', 'ibrahim', 'kaaba'],
  15: ['hijr', 'roche'],
  16: ['abeilles', 'nahl', 'miel'],
  17: ['isra', 'voyage', 'jerusalem', 'nuit', 'ascension'],
  18: ['caverne', 'kahf', 'dajjal', 'dhu al qarnayn', 'alexandre', 'jeunes gens'],
  19: ['marie', 'mariam', 'jesus', 'jean', 'zacharie'],
  20: ['ta-ha', 'moise', 'moussa', 'pharaon'],
  21: ['prophetes', 'anbiya', 'job', 'ayyoub', 'zacharie'],
  22: ['pelerinage', 'hajj', 'kaaba'],
  23: ['croyants', 'muminun', 'foi'],
  24: ['lumiere', 'nur', 'pudeur', 'chastete'],
  25: ['discernement', 'furqan', 'criteres'],
  26: ['poetes', 'shuara'],
  27: ['fourmis', 'naml', 'salomon', 'souleymane', 'saba'],
  28: ['recit', 'qasas', 'moise', 'qarun', 'core'],
  29: ['araignee', 'ankabut'],
  30: ['romains', 'rum', 'byzance'],
  31: ['luqman', 'sagesse', 'parents'],
  32: ['prosternation', 'sajda', 'creation'],
  33: ['coalises', 'ahzab', 'factions'],
  34: ['saba', 'david', 'salomon'],
  35: ['createur', 'fatir', 'anges'],
  36: ['ya-sin', 'yassine', 'yasin', 'coeur'],
  37: ['ranges', 'saffat'],
  38: ['sad', 'david', 'daoud', 'salomon', 'job'],
  39: ['groupes', 'zumar'],
  40: ['pardonneur', 'ghafir', 'moise', 'pharaon'],
  41: ['detail', 'fussilat', 'versets'],
  42: ['concertation', 'choura', 'conseil'],
  43: ['ornement', 'zakhruf', 'or'],
  44: ['fumee', 'dukhan'],
  45: ['agenouillee', 'jathiya'],
  46: ['dunes', 'ahqaf', 'aad'],
  47: ['muhammad', 'combat'],
  48: ['victoire', 'fath', 'hudaybiya'],
  49: ['appartements', 'hujurat', 'respect', 'politesse'],
  50: ['qaf'],
  51: ['eparpilles', 'dhariyat', 'vents'],
  52: ['mont', 'tur', 'sinai'],
  53: ['etoile', 'najm', 'ascension'],
  54: ['lune', 'qamar'],
  55: ['misericordieux', 'rahman', 'bienfaits', 'merci'],
  56: ['evenement', 'waqia', 'jugement'],
  57: ['fer', 'hadid'],
  58: ['discussion', 'mujadala', 'plainte'],
  59: ['exode', 'hashr', 'exil'],
  60: ['eprouvee', 'mumtahana'],
  61: ['rang', 'saff', 'jesus'],
  62: ['vendredi', 'jumua', 'priere'],
  63: ['hypocrites', 'munafiqun'],
  64: ['perte', 'taghabun', 'tromperie'],
  65: ['divorce', 'talaq'],
  66: ['interdiction', 'tahrim'],
  67: ['royaute', 'mulk', 'souverainete', 'protection'],
  68: ['plume', 'qalam', 'ecriture'],
  69: ['inevitable', 'haqqa'],
  70: ['ascension', 'maarij', 'degres'],
  71: ['noe', 'nuh', 'deluge'],
  72: ['djinns', 'jinn', 'genies'],
  73: ['enveloppe', 'muzzammil', 'nuit'],
  74: ['manteau', 'muddaththir'],
  75: ['resurrection', 'qiyama', 'jugement'],
  76: ['homme', 'insan', 'paradis'],
  77: ['envoyees', 'mursalat', 'vents'],
  78: ['nouvelle', 'naba', 'annonce'],
  79: ['arracheurs', 'naziat'],
  80: ['renfrogne', 'abasa', 'aveugle'],
  81: ['obscurcissement', 'takwir', 'soleil'],
  82: ['rupture', 'infitar'],
  83: ['fraudeurs', 'mutaffifin', 'poids', 'mesure'],
  84: ['dechirure', 'inshiqaq'],
  85: ['constellations', 'buruj', 'etoiles'],
  86: ['astre', 'tariq', 'etoile', 'nuit'],
  87: ['tres-haut', 'ala'],
  88: ['enveloppante', 'ghashiya', 'visages'],
  89: ['aube', 'fajr', 'aube'],
  90: ['cite', 'balad', 'ville'],
  91: ['soleil', 'shams', 'ame'],
  92: ['nuit', 'layl'],
  93: ['jour', 'duha', 'matin'],
  94: ['ouverture', 'sharh', 'consolation', 'poitrine'],
  95: ['figuier', 'tin'],
  96: ['adherence', 'alaq', 'caillot', 'lecture', 'iqra'],
  97: ['destinee', 'qadr', 'nuit du destin'],
  98: ['preuve', 'bayyina', 'livre'],
  99: ['secousse', 'zalzala', 'tremblement', 'terre'],
  100: ['coursiers', 'adiyat', 'chevaux'],
  101: ['fracas', 'qaria', 'catastrophe'],
  102: ['richesses', 'takathur', 'avarice'],
  103: ['temps', 'asr', 'apres-midi'],
  104: ['calomniateurs', 'humaza', 'medisants'],
  105: ['elephant', 'fil', 'abraha'],
  106: ['quraysh', 'cureish', 'tribu'],
  107: ['ustensile', 'maun', 'orphelin', 'aumone'],
  108: ['abondance', 'kawthar', 'paradis'],
  109: ['mecreants', 'kafirun'],
  110: ['secours', 'nasr', 'victoire', 'conquete'],
  111: ['fibres', 'masad', 'abu lahab'],
  112: ['monotheisme', 'ikhlas', 'sincerite', 'unicite'],
  113: ['aube', 'falaq', 'protection'],
  114: ['hommes', 'nas', 'gens', 'protection'],
};
